#!/usr/bin/env bash

set -eu

if [[ $# -gt 0 && "$1" = "rustdoc-clippy" ]]
then
  shift

  if [[ $# -gt 0 && "$1" = "--help" ]]
  then
    echo "USAGE: cargo rustdoc-clippy [cargo-options] [-- [rustdoc-options] [-- [clippy-options]]]"
    exit
  fi

  cargo_args=()
  while [[ $# -gt 0 && "$1" != "--" ]]
  do
    cargo_args+=("$1")
    shift
  done

  if [[ $# -gt 0 ]]
  then
    shift
  fi

  rustdoc_args=()
  while [[ $# -gt 0 && "$1" != "--" ]]
  do
    rustdoc_args+=("$1")
    shift
  done

  if [[ $# -gt 0 ]]
  then
    shift
  fi

  clippy_args=()
  while [[ $# -gt 0 ]]
  do
    clippy_args+=("$1")
    shift
  done

  CLIPPYFLAGS="$(IFS="\x1E"; echo "${clippy_args[*]}")" RUSTDOCFLAGS="-Z unstable-options --no-run --no-capture --test-builder "$0"  ${rustdoc_args[@]}" exec cargo test --verbose --doc "${cargo_args[@]}"
else
  if [[ "$CLIPPYFLAGS" != "" ]]
  then
    IFS=$'\x1E' read -r -a clippyflags <<< "$CLIPPYFLAGS"
    exec clippy-driver "${clippyflags[@]}" "$@"
  else
    exec clippy-driver "${@}"
  fi
fi
